prog:background.o bouton.o time.o scrolling.o enemie.o CollisionParfaite.o vie_score.o perso.o main.o
	gcc background.o bouton.o time.o scrolling.o enemie.o CollisionParfaite.o vie_score.o perso.o main.o -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer -lSDL_gfx -o prog
main.o:main.c
	gcc -c main.c
perso.o:perso.c
	gcc -c perso.c
vie_score.o:vie_score.c
	gcc -c vie_score.c
CollisionParfaite.o:CollisionParfaite.c
	gcc -c CollisionParfaite.c
enemie.o:enemie.c
	gcc -c enemie.c
scrolling.o:scrolling.c
	gcc -c scrolling.c
time.o:time.c
	gcc -c time.c
bouton.o:bouton.c
	gcc -c bouton.c
background.o:background.c
	gcc -c background.c

